name: Hello World Workflow

on:
  push:
    branches:
      - main

jobs:
  hello-world:
    runs-on: ubuntu-latest

    steps:
    - name: Show Hello World message
      run: echo "Hello, World!"
    - name: show list of dirrectory
      run: ls
    - name: Read the file
      run: cat readme.md

